# Generated by Django 3.2.16 on 2025-02-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='chat_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
