# Generated by Django 3.2.16 on 2025-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_processor', '0002_transcript_chat_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=10)),
                ('chat_role', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='content',
            new_name='raw_content',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='chat_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transcript',
            name='speaker_mapping',
            field=models.ManyToManyField(blank=True, to='batch_processor.SpeakerMap'),
        ),
    ]
