# Generated by Django 5.1.6 on 2025-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_processor', '0005_remove_speakermap_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='asr_segments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='missing_segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
