# Generated by Django 5.1.6 on 2025-02-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_processor', '0006_transcript_asr_segments_transcript_missing_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='asr_segments',
        ),
        migrations.AddField(
            model_name='transcript',
            name='pyannote_processed',
            field=models.BooleanField(default=False),
        ),
    ]
