# Generated by Django 5.1.6 on 2025-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_processor', '0007_remove_transcript_asr_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='format',
            field=models.CharField(default='CHAT', max_length=20),
        ),
    ]
