# Generated by Django 5.1.6 on 2025-05-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch_processor', '0008_transcript_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcedAlignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_timestamps', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('engine_used', models.CharField(choices=[('WHISPER', 'WhisperFA'), ('WAV2VEC', 'Wave2VecFA'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_tasks', to='batch_processor.transcript')),
            ],
            options={
                'verbose_name': 'Forced Alignment Task',
                'verbose_name_plural': 'Forced Alignment Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
