# Generated by Django 5.1.6 on 2025-05-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forced_alignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forcedalignmenttask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='forcedalignmenttask',
            name='engine_used',
            field=models.CharField(choices=[('WHISPER', 'WhisperFA'), ('WAV2VEC', 'Wave2VecFA'), ('AUTO', 'Auto')], default='AUTO', max_length=20),
        ),
    ]
