# Generated by Django 5.1.6 on 2025-05-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_processor', '0008_transcript_format'),
        ('forced_alignment', '0002_alter_forcedalignmenttask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcedalignmenttask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='forced_alignment/audio/'),
        ),
        migrations.AddField(
            model_name='forcedalignmenttask',
            name='cha_file',
            field=models.FileField(blank=True, null=True, upload_to='forced_alignment/cha/'),
        ),
        migrations.AddField(
            model_name='forcedalignmenttask',
            name='title',
            field=models.CharField(default='Untitled Alignment', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forcedalignmenttask',
            name='original_transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_tasks', to='batch_processor.transcript'),
        ),
    ]
