# Generated by Django 5.1.6 on 2025-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forced_alignment', '0003_add_file_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcedalignmenttask',
            name='title',
            field=models.CharField(default='Untitled Alignment', max_length=255),
        ),
    ]
